### ISSUE TITLE
First input byte in 04-crash-analysis/08

### ISSUE THREAD

**Issue by dingiso** [fuzzware-fuzzer/fuzzware#14]
I have encountered a curious problem which have bothered me for hours. Ask for help :sob:

I'm working on how unicorn accept the input from fuzz. I compared the crashing_input with the log generated by replay command and everything goes right except the **first byte**

this log entry is like this 
```
>>> Read: addr= 0x0000000040023808 size=4 data=0x00000000 (pc 0x08001b04)
```

and the model generated by fuzzware is 
```
set:
    pc_08001b04_mmio_40023808:
      access_size: 0x4
      addr: 0x40023808
      pc: 0x8001b04
      vals:
      - 0x0
      - 0x4
      - 0x8
```

the first byte generated by fuzzer is **0x20** so the data should be
```
data = vals[0x20 % len(vals)]
     = vals[32 % 3]
     = vals[2]
     = 0x8
```
But the data in log is **0x0**.  Other read operations are all right , so I think it's not my model's wrong. 
Is there any hints or something I misunderstood ? 

Thanks.
